[package]
name = "polymodo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.95"
log-panics = "2.1.0"
rust-ini = "0.21.1"
strum = { version = "0.26.3", features = ["derive"] }
xdg = "2.5.2"
nucleo = "0.5.0"
windowing = { path = "windowing" }

[workspace]
members = ["windowing"]
